window.POCHO_DATA = {
  "behaviorRules": [
    {
      "id": "size-2",
      "layer": "size",
      "priority": 1,
      "attribute": "小",
      "result": "STICK",
      "condition": "相手も小 ＋ 低速接触",
      "conditionCount": 2,
      "active": true,
      "status": "active"
    },
    {
      "id": "size-3",
      "layer": "size",
      "priority": 1,
      "attribute": "小",
      "result": "STICK",
      "condition": "相手が中 ＋ 自分の速度が低い",
      "conditionCount": 2,
      "active": true,
      "status": "active"
    },
    {
      "id": "size-4",
      "layer": "size",
      "priority": 1,
      "attribute": "小",
      "result": "STICK",
      "condition": "相手が大 ＋ 接触後ほぼ停止状態になる",
      "conditionCount": 2,
      "active": true,
      "status": "active"
    },
    {
      "id": "size-5",
      "layer": "size",
      "priority": 1,
      "attribute": "小",
      "result": "POP",
      "condition": "相手が大 ＋ 自分が高速で衝突 ＋ 弾け補正：相対速度8.8以上",
      "conditionCount": 3,
      "active": false,
      "status": "disabled",
      "burstTuning": "v0.1.4: 一時無効化（大きさPOP全停止）",
      "disabledReason": "v0.1.4検証: 大きさレイヤーの弾け条件を一時的に全無効化。弾け頻度の主因切り分け用。"
    },
    {
      "id": "size-6",
      "layer": "size",
      "priority": 1,
      "attribute": "小",
      "result": "POP",
      "condition": "相手が大 ＋ サイズ差がかなり大きい ＋ 相対速度が一定以上 ＋ 弾け補正：相対速度8.8以上",
      "conditionCount": 4,
      "active": false,
      "status": "disabled",
      "burstTuning": "v0.1.4: 一時無効化（大きさPOP全停止）",
      "disabledReason": "v0.1.4検証: 大きさレイヤーの弾け条件を一時的に全無効化。弾け頻度の主因切り分け用。"
    },
    {
      "id": "size-7",
      "layer": "size",
      "priority": 1,
      "attribute": "中",
      "result": "STICK",
      "condition": "相手も中 ＋ 低速接触",
      "conditionCount": 2,
      "active": true,
      "status": "active"
    },
    {
      "id": "size-8",
      "layer": "size",
      "priority": 1,
      "attribute": "中",
      "result": "STICK",
      "condition": "相手とのサイズ差が非常に小さい ＋ 相対速度が低い",
      "conditionCount": 2,
      "active": true,
      "status": "active"
    },
    {
      "id": "size-9",
      "layer": "size",
      "priority": 1,
      "attribute": "中",
      "result": "STICK",
      "condition": "相手が小 ＋ 自分がほぼ停止している",
      "conditionCount": 2,
      "active": true,
      "status": "active"
    },
    {
      "id": "size-10",
      "layer": "size",
      "priority": 1,
      "attribute": "中",
      "result": "POP",
      "condition": "相手が大 ＋ 高速正面衝突 ＋ 弾け補正：相対速度8.8以上",
      "conditionCount": 3,
      "active": false,
      "status": "disabled",
      "burstTuning": "v0.1.4: 一時無効化（大きさPOP全停止）",
      "disabledReason": "v0.1.4検証: 大きさレイヤーの弾け条件を一時的に全無効化。弾け頻度の主因切り分け用。"
    },
    {
      "id": "size-11",
      "layer": "size",
      "priority": 1,
      "attribute": "中",
      "result": "POP",
      "condition": "相手も中 ＋ 両方とも高速 ＋ 弾け補正：相対速度8.8以上",
      "conditionCount": 3,
      "active": false,
      "status": "disabled",
      "burstTuning": "v0.1.4: 一時無効化（大きさPOP全停止）",
      "disabledReason": "v0.1.4検証: 大きさレイヤーの弾け条件を一時的に全無効化。弾け頻度の主因切り分け用。"
    },
    {
      "id": "size-12",
      "layer": "size",
      "priority": 1,
      "attribute": "大",
      "result": "STICK",
      "condition": "相手も大 ＋ かなり低速",
      "conditionCount": 2,
      "active": true,
      "status": "active"
    },
    {
      "id": "size-13",
      "layer": "size",
      "priority": 1,
      "attribute": "大",
      "result": "STICK",
      "condition": "相手が小 ＋ 大きい方がほぼ停止",
      "conditionCount": 2,
      "active": true,
      "status": "active"
    },
    {
      "id": "size-14",
      "layer": "size",
      "priority": 1,
      "attribute": "大",
      "result": "STICK",
      "condition": "相手が中 ＋ サイズ差が小さめ ＋ 低速接触",
      "conditionCount": 3,
      "active": true,
      "status": "active"
    },
    {
      "id": "size-15",
      "layer": "size",
      "priority": 1,
      "attribute": "大",
      "result": "POP",
      "condition": "相手も大 ＋ 高速衝突 ＋ 弾け補正：相対速度8.8以上",
      "conditionCount": 3,
      "active": false,
      "status": "disabled",
      "burstTuning": "v0.1.4: 一時無効化（大きさPOP全停止）",
      "disabledReason": "v0.1.4検証: 大きさレイヤーの弾け条件を一時的に全無効化。弾け頻度の主因切り分け用。"
    },
    {
      "id": "size-16",
      "layer": "size",
      "priority": 1,
      "attribute": "大",
      "result": "POP",
      "condition": "相手が小 ＋ 小さい方が非常に高速 ＋ 弾け補正：相対速度8.8以上",
      "conditionCount": 3,
      "active": false,
      "status": "disabled",
      "burstTuning": "v0.1.4: 一時無効化（大きさPOP全停止）",
      "disabledReason": "v0.1.4検証: 大きさレイヤーの弾け条件を一時的に全無効化。弾け頻度の主因切り分け用。"
    },
    {
      "id": "size-17",
      "layer": "size",
      "priority": 1,
      "attribute": "大",
      "result": "POP",
      "condition": "相手が中以上 ＋ 自分が壁接触直後 ＋ 高速衝突 ＋ 弾け補正：相対速度8.8以上",
      "conditionCount": 4,
      "active": false,
      "status": "disabled",
      "burstTuning": "v0.1.4: 一時無効化（大きさPOP全停止）",
      "disabledReason": "v0.1.4検証: 大きさレイヤーの弾け条件を一時的に全無効化。弾け頻度の主因切り分け用。"
    },
    {
      "id": "color-2",
      "layer": "color",
      "priority": 2,
      "attribute": "さくら",
      "result": "STICK",
      "condition": "相手がさくら ＋ 相対速度が低い ＋ 過去に一度以上接触済み",
      "conditionCount": 3,
      "active": true,
      "status": "active"
    },
    {
      "id": "color-3",
      "layer": "color",
      "priority": 2,
      "attribute": "さくら",
      "result": "STICK",
      "condition": "相手が異色 ＋ 同じ相手との接触が3回目以上 ＋ 現在どちらも低速",
      "conditionCount": 3,
      "active": true,
      "status": "active"
    },
    {
      "id": "color-4",
      "layer": "color",
      "priority": 2,
      "attribute": "さくら",
      "result": "STICK",
      "condition": "相手と一度離れた履歴あり ＋ 再接触 ＋ 接触地点が画面上半分",
      "conditionCount": 3,
      "active": true,
      "status": "active"
    },
    {
      "id": "color-5",
      "layer": "color",
      "priority": 2,
      "attribute": "さくら",
      "result": "STICK",
      "condition": "相手とのサイズ差が小さい ＋ 直前に別のぽちょへ触れていない ＋ 接触時間が一定以上",
      "conditionCount": 3,
      "active": false,
      "status": "unimplemented",
      "missing": "接触継続時間の計測が未実装"
    },
    {
      "id": "color-6",
      "layer": "color",
      "priority": 2,
      "attribute": "さくら",
      "result": "STICK",
      "condition": "相手がごきげん ＋ 自分もごきげん ＋ 相対速度が一定以下",
      "conditionCount": 3,
      "active": true,
      "status": "active"
    },
    {
      "id": "color-7",
      "layer": "color",
      "priority": 2,
      "attribute": "さくら",
      "result": "STICK",
      "condition": "過去に同じグループだった ＋ 現在は離れている ＋ 再接触時の速度が低い",
      "conditionCount": 3,
      "active": true,
      "status": "active"
    },
    {
      "id": "color-8",
      "layer": "color",
      "priority": 2,
      "attribute": "さくら",
      "result": "POP",
      "condition": "相手がさくら ＋ 互いに過去3回以上接触 ＋ 今回だけ高速衝突 ＋ 弾け補正：相対速度7.8以上",
      "conditionCount": 4,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.8以上"
    },
    {
      "id": "color-9",
      "layer": "color",
      "priority": 2,
      "attribute": "さくら",
      "result": "POP",
      "condition": "一度くっついた相手 ＋ 再接触 ＋ 今回の表情が前回接着時と違う ＋ 弾け補正：相対速度7.8以上",
      "conditionCount": 4,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.8以上"
    },
    {
      "id": "color-10",
      "layer": "color",
      "priority": 2,
      "attribute": "さくら",
      "result": "POP",
      "condition": "相手が異色 ＋ 自分が天井接触済み ＋ 接触直前の速度が高い ＋ 弾け補正：相対速度7.8以上",
      "conditionCount": 4,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.8以上"
    },
    {
      "id": "color-11",
      "layer": "color",
      "priority": 2,
      "attribute": "さくら",
      "result": "POP",
      "condition": "同じ相手と短時間に何度も衝突 ＋ その相手と一度もくっついていない ＋ 今回が高速 ＋ 弾け補正：相対速度7.8以上",
      "conditionCount": 4,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.8以上"
    },
    {
      "id": "color-12",
      "layer": "color",
      "priority": 2,
      "attribute": "みずいろ",
      "result": "STICK",
      "condition": "壁接触2回以上 ＋ 現在低速 ＋ 相手が自分より大きい",
      "conditionCount": 3,
      "active": true,
      "status": "active"
    },
    {
      "id": "color-13",
      "layer": "color",
      "priority": 2,
      "attribute": "みずいろ",
      "result": "STICK",
      "condition": "射出後一定距離以上移動済み ＋ 初めて触れる相手 ＋ 接触速度が低い",
      "conditionCount": 3,
      "active": true,
      "status": "active"
    },
    {
      "id": "color-14",
      "layer": "color",
      "priority": 2,
      "attribute": "みずいろ",
      "result": "STICK",
      "condition": "天井に一度触れている ＋ 相手も天井接触済み ＋ 相対速度が低い",
      "conditionCount": 3,
      "active": true,
      "status": "active"
    },
    {
      "id": "color-15",
      "layer": "color",
      "priority": 2,
      "attribute": "みずいろ",
      "result": "STICK",
      "condition": "左右両方の壁に触れた履歴あり ＋ 異色相手 ＋ 接触時にほぼ同じ方向へ移動",
      "conditionCount": 3,
      "active": true,
      "status": "active"
    },
    {
      "id": "color-16",
      "layer": "color",
      "priority": 2,
      "attribute": "みずいろ",
      "result": "STICK",
      "condition": "高速状態を経験済み ＋ 現在は低速 ＋ 相手が停止に近い",
      "conditionCount": 3,
      "active": true,
      "status": "active"
    },
    {
      "id": "color-17",
      "layer": "color",
      "priority": 2,
      "attribute": "みずいろ",
      "result": "POP",
      "condition": "壁接触3回以上 ＋ 異色相手 ＋ 高速衝突 ＋ 弾け補正：相対速度7.8以上",
      "conditionCount": 4,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.8以上"
    },
    {
      "id": "color-18",
      "layer": "color",
      "priority": 2,
      "attribute": "みずいろ",
      "result": "POP",
      "condition": "射出から短時間 ＋ 壁に一度も触れていない ＋ 高速で他ぽちょに接触 ＋ 弾け補正：相対速度7.8以上",
      "conditionCount": 4,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.8以上"
    },
    {
      "id": "color-19",
      "layer": "color",
      "priority": 2,
      "attribute": "みずいろ",
      "result": "POP",
      "condition": "天井接触直後 ＋ 下方向へ動いている相手 ＋ 相対速度が高い ＋ 弾け補正：相対速度7.8以上",
      "conditionCount": 4,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.8以上"
    },
    {
      "id": "color-20",
      "layer": "color",
      "priority": 2,
      "attribute": "みずいろ",
      "result": "POP",
      "condition": "左壁→右壁の順に触れた直後 ＋ 他ぽちょへ接触 ＋ 現在速度が一定以上 ＋ 弾け補正：相対速度7.8以上",
      "conditionCount": 4,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.8以上"
    },
    {
      "id": "color-21",
      "layer": "color",
      "priority": 2,
      "attribute": "みずいろ",
      "result": "POP",
      "condition": "累計移動距離が長い ＋ 同じ相手に再接触 ＋ 今回の速度が過去接触時より高い ＋ 弾け補正：相対速度7.8以上",
      "conditionCount": 4,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.8以上"
    },
    {
      "id": "color-22",
      "layer": "color",
      "priority": 2,
      "attribute": "みずいろ",
      "result": "POP",
      "condition": "直前の接触相手と別の色 ＋ 高速衝突 ＋ 壁際 ＋ 弾け補正：相対速度7.8以上",
      "conditionCount": 4,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.8以上"
    },
    {
      "id": "color-23",
      "layer": "color",
      "priority": 2,
      "attribute": "たまご",
      "result": "STICK",
      "condition": "同じ相手との3回目の接触 ＋ 低速 ＋ 相手が異色",
      "conditionCount": 3,
      "active": true,
      "status": "active"
    },
    {
      "id": "color-24",
      "layer": "color",
      "priority": 2,
      "attribute": "たまご",
      "result": "STICK",
      "condition": "総接触回数が5回以上 ＋ 今回の相手が初対面 ＋ 接触速度が低い",
      "conditionCount": 3,
      "active": true,
      "status": "active"
    },
    {
      "id": "color-25",
      "layer": "color",
      "priority": 2,
      "attribute": "たまご",
      "result": "STICK",
      "condition": "壁接触回数が偶数 ＋ 相手とのサイズ差が小さい ＋ 画面上半分",
      "conditionCount": 3,
      "active": true,
      "status": "active"
    },
    {
      "id": "color-26",
      "layer": "color",
      "priority": 2,
      "attribute": "たまご",
      "result": "STICK",
      "condition": "自分がゲーム内で奇数番目に射出 ＋ 相手が偶数番目 ＋ 低速接触",
      "conditionCount": 3,
      "active": true,
      "status": "active"
    },
    {
      "id": "color-27",
      "layer": "color",
      "priority": 2,
      "attribute": "たまご",
      "result": "STICK",
      "condition": "直近3回の接触相手がすべて異なる ＋ 今回が4色目 ＋ 相対速度が低い",
      "conditionCount": 3,
      "active": true,
      "status": "active"
    },
    {
      "id": "color-28",
      "layer": "color",
      "priority": 2,
      "attribute": "たまご",
      "result": "STICK",
      "condition": "同色への接触が今回で2回目 ＋ 相手もたまご ＋ どちらも高速ではない",
      "conditionCount": 3,
      "active": true,
      "status": "active"
    },
    {
      "id": "color-29",
      "layer": "color",
      "priority": 2,
      "attribute": "たまご",
      "result": "POP",
      "condition": "同じ相手との5回目の接触 ＋ 高速 ＋ 相手が異色 ＋ 弾け補正：相対速度7.8以上",
      "conditionCount": 4,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.8以上"
    },
    {
      "id": "color-30",
      "layer": "color",
      "priority": 2,
      "attribute": "たまご",
      "result": "POP",
      "condition": "総接触回数が7回以上 ＋ 今回が同色接触 ＋ 壁際 ＋ 弾け補正：相対速度7.8以上",
      "conditionCount": 4,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.8以上"
    },
    {
      "id": "color-31",
      "layer": "color",
      "priority": 2,
      "attribute": "たまご",
      "result": "POP",
      "condition": "壁接触回数が3の倍数 ＋ 異色相手 ＋ 高速接触 ＋ 弾け補正：相対速度7.8以上",
      "conditionCount": 4,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.8以上"
    },
    {
      "id": "color-32",
      "layer": "color",
      "priority": 2,
      "attribute": "たまご",
      "result": "POP",
      "condition": "射出順が相手と3つ差 ＋ 接触速度が一定以上 ＋ どちらかが天井接触済み ＋ 弾け補正：相対速度7.8以上",
      "conditionCount": 4,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.8以上"
    },
    {
      "id": "color-33",
      "layer": "color",
      "priority": 2,
      "attribute": "たまご",
      "result": "POP",
      "condition": "直近の接触色が「異色→異色→自色」 ＋ 今回も自色 ＋ 高速 ＋ 弾け補正：相対速度7.8以上",
      "conditionCount": 4,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.8以上"
    },
    {
      "id": "color-34",
      "layer": "color",
      "priority": 2,
      "attribute": "たまご",
      "result": "POP",
      "condition": "生存中にちょうど3種類の色と接触済み ＋ 4種類目へ接触 ＋ 高速 ＋ 弾け補正：相対速度7.8以上",
      "conditionCount": 4,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.8以上"
    },
    {
      "id": "color-35",
      "layer": "color",
      "priority": 2,
      "attribute": "わかば",
      "result": "STICK",
      "condition": "生存時間が一定以上 ＋ 一度も弾け条件未成立 ＋ 低速接触",
      "conditionCount": 3,
      "active": true,
      "status": "active"
    },
    {
      "id": "color-36",
      "layer": "color",
      "priority": 2,
      "attribute": "わかば",
      "result": "STICK",
      "condition": "表情変化経験あり ＋ 変化後初めての接触 ＋ 相手が異色",
      "conditionCount": 3,
      "active": true,
      "status": "active"
    },
    {
      "id": "color-37",
      "layer": "color",
      "priority": 2,
      "attribute": "わかば",
      "result": "STICK",
      "condition": "一度くっついた履歴あり ＋ 現在単独 ＋ 低速で別相手に接触",
      "conditionCount": 3,
      "active": true,
      "status": "active"
    },
    {
      "id": "color-38",
      "layer": "color",
      "priority": 2,
      "attribute": "わかば",
      "result": "STICK",
      "condition": "長時間他ぽちょと接触していない ＋ 新しい相手 ＋ 接触速度が低い",
      "conditionCount": 3,
      "active": true,
      "status": "active"
    },
    {
      "id": "color-39",
      "layer": "color",
      "priority": 2,
      "attribute": "わかば",
      "result": "STICK",
      "condition": "壁接触回数が少ない ＋ 生存時間が長い ＋ 相手が自分より小さい",
      "conditionCount": 3,
      "active": true,
      "status": "active"
    },
    {
      "id": "color-40",
      "layer": "color",
      "priority": 2,
      "attribute": "わかば",
      "result": "STICK",
      "condition": "過去に3種類以上の色と接触済み ＋ 今回の相手が未接触色 ＋ 低速",
      "conditionCount": 3,
      "active": true,
      "status": "active"
    },
    {
      "id": "color-41",
      "layer": "color",
      "priority": 2,
      "attribute": "わかば",
      "result": "POP",
      "condition": "生存時間が長い ＋ 高速衝突 ＋ 相手が自分より大きい ＋ 弾け補正：相対速度7.8以上",
      "conditionCount": 4,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.8以上"
    },
    {
      "id": "color-42",
      "layer": "color",
      "priority": 2,
      "attribute": "わかば",
      "result": "POP",
      "condition": "表情変化2回以上 ＋ 異色接触 ＋ 相対速度が一定以上 ＋ 弾け補正：相対速度7.8以上",
      "conditionCount": 4,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.8以上"
    },
    {
      "id": "color-43",
      "layer": "color",
      "priority": 2,
      "attribute": "わかば",
      "result": "POP",
      "condition": "一度くっついて離れた履歴あり ＋ 別グループに接触 ＋ 高速 ＋ 弾け補正：相対速度7.8以上",
      "conditionCount": 4,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.8以上"
    },
    {
      "id": "color-44",
      "layer": "color",
      "priority": 2,
      "attribute": "わかば",
      "result": "POP",
      "condition": "長時間静止した後 ＋ 初回衝突 ＋ 相手が高速 ＋ 弾け補正：相対速度7.8以上",
      "conditionCount": 4,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.8以上"
    },
    {
      "id": "color-45",
      "layer": "color",
      "priority": 2,
      "attribute": "わかば",
      "result": "POP",
      "condition": "サイズが一度変化した履歴あり ＋ 同色相手 ＋ 高速接触 ＋ 弾け補正：相対速度7.8以上",
      "conditionCount": 4,
      "active": false,
      "status": "unimplemented",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.8以上"
    },
    {
      "id": "color-46",
      "layer": "color",
      "priority": 2,
      "attribute": "ふじ",
      "result": "STICK",
      "condition": "周囲に3色以上存在 ＋ 相手が異色 ＋ 低速接触",
      "conditionCount": 3,
      "active": true,
      "status": "active"
    },
    {
      "id": "color-47",
      "layer": "color",
      "priority": 2,
      "attribute": "ふじ",
      "result": "STICK",
      "condition": "接触地点の近くにぽちょが3体以上 ＋ 相手とのサイズ差が小さい ＋ 低速",
      "conditionCount": 3,
      "active": true,
      "status": "active"
    },
    {
      "id": "color-48",
      "layer": "color",
      "priority": 2,
      "attribute": "ふじ",
      "result": "STICK",
      "condition": "相手が現在2体以上と接触中 ＋ 自分は単独 ＋ 低速で接触",
      "conditionCount": 3,
      "active": true,
      "status": "active"
    },
    {
      "id": "color-49",
      "layer": "color",
      "priority": 2,
      "attribute": "ふじ",
      "result": "STICK",
      "condition": "周囲に同表情が2体以上 ＋ 相手がその表情と異なる ＋ 相対速度が低い",
      "conditionCount": 3,
      "active": true,
      "status": "active"
    },
    {
      "id": "color-50",
      "layer": "color",
      "priority": 2,
      "attribute": "ふじ",
      "result": "STICK",
      "condition": "画面上半分 ＋ 周囲に自分と同色がいない ＋ 異色相手に接触",
      "conditionCount": 3,
      "active": true,
      "status": "active"
    },
    {
      "id": "color-51",
      "layer": "color",
      "priority": 2,
      "attribute": "ふじ",
      "result": "STICK",
      "condition": "相手の周囲に自分以外のふじがいる ＋ 今回が初接触 ＋ 低速",
      "conditionCount": 3,
      "active": true,
      "status": "active"
    },
    {
      "id": "color-52",
      "layer": "color",
      "priority": 2,
      "attribute": "ふじ",
      "result": "POP",
      "condition": "周囲に4色以上存在 ＋ 高速衝突 ＋ 相手が異色 ＋ 弾け補正：相対速度7.8以上",
      "conditionCount": 4,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.8以上"
    },
    {
      "id": "color-53",
      "layer": "color",
      "priority": 2,
      "attribute": "ふじ",
      "result": "POP",
      "condition": "接触地点の近くに4体以上 ＋ 相手が自分より大きい ＋ 相対速度が高い ＋ 弾け補正：相対速度7.8以上",
      "conditionCount": 4,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.8以上"
    },
    {
      "id": "color-54",
      "layer": "color",
      "priority": 2,
      "attribute": "ふじ",
      "result": "POP",
      "condition": "自分がグループの端 ＋ グループ内に3色以上 ＋ 高速接触 ＋ 弾け補正：相対速度7.8以上",
      "conditionCount": 4,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.8以上"
    },
    {
      "id": "color-55",
      "layer": "color",
      "priority": 2,
      "attribute": "ふじ",
      "result": "POP",
      "condition": "周囲のぽちょの表情が全てバラバラ ＋ 異色接触 ＋ 壁際 ＋ 弾け補正：相対速度7.8以上",
      "conditionCount": 4,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.8以上"
    },
    {
      "id": "color-56",
      "layer": "color",
      "priority": 2,
      "attribute": "ふじ",
      "result": "POP",
      "condition": "直前に周囲で別のぽちょが弾けた ＋ 一定時間以内 ＋ 高速接触 ＋ 弾け補正：相対速度7.8以上",
      "conditionCount": 4,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.8以上"
    },
    {
      "id": "color-57",
      "layer": "color",
      "priority": 2,
      "attribute": "ふじ",
      "result": "POP",
      "condition": "周囲に同色が2体以上いるのに自分だけ単独 ＋ 異色相手 ＋ 高速 ＋ 弾け補正：相対速度7.8以上",
      "conditionCount": 4,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.8以上"
    },
    {
      "id": "color-58",
      "layer": "color",
      "priority": 2,
      "attribute": "あんず",
      "result": "STICK",
      "condition": "相対速度が低い ＋ 接触角度が浅い ＋ 相手が自分より大きい",
      "conditionCount": 3,
      "active": true,
      "status": "active"
    },
    {
      "id": "color-59",
      "layer": "color",
      "priority": 2,
      "attribute": "あんず",
      "result": "STICK",
      "condition": "自分がほぼ停止 ＋ 相手から押されて接触 ＋ サイズ差が小さい",
      "conditionCount": 3,
      "active": true,
      "status": "active"
    },
    {
      "id": "color-60",
      "layer": "color",
      "priority": 2,
      "attribute": "あんず",
      "result": "STICK",
      "condition": "直前に別ぽちょへ衝突済み ＋ その反動で今回の相手に接触 ＋ 低速",
      "conditionCount": 3,
      "active": true,
      "status": "active"
    },
    {
      "id": "color-61",
      "layer": "color",
      "priority": 2,
      "attribute": "あんず",
      "result": "STICK",
      "condition": "自分が小 ＋ 相手が大 ＋ 接触後の速度が急激に低下",
      "conditionCount": 3,
      "active": true,
      "status": "active"
    },
    {
      "id": "color-62",
      "layer": "color",
      "priority": 2,
      "attribute": "あんず",
      "result": "POP",
      "condition": "相対速度が高い ＋ 正面に近い衝突 ＋ 相手が同等以上のサイズ ＋ 弾け補正：相対速度7.8以上",
      "conditionCount": 4,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.8以上"
    },
    {
      "id": "color-63",
      "layer": "color",
      "priority": 2,
      "attribute": "あんず",
      "result": "POP",
      "condition": "小さいあんず ＋ 大きい相手 ＋ 高速で自分から衝突 ＋ 弾け補正：相対速度7.8以上",
      "conditionCount": 4,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.8以上"
    },
    {
      "id": "color-64",
      "layer": "color",
      "priority": 2,
      "attribute": "あんず",
      "result": "POP",
      "condition": "壁反射直後 ＋ 異色相手 ＋ 高速接触 ＋ 弾け補正：相対速度7.8以上",
      "conditionCount": 4,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.8以上"
    },
    {
      "id": "color-65",
      "layer": "color",
      "priority": 2,
      "attribute": "あんず",
      "result": "POP",
      "condition": "直前の衝突から短時間以内 ＋ 別の相手へ再度高速衝突 ＋ 相手が異色 ＋ 弾け補正：相対速度7.8以上",
      "conditionCount": 4,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.8以上"
    },
    {
      "id": "color-66",
      "layer": "color",
      "priority": 2,
      "attribute": "あんず",
      "result": "POP",
      "condition": "自分が大 ＋ 相手も大 ＋ 双方が移動中 ＋ 弾け補正：相対速度7.8以上",
      "conditionCount": 4,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.8以上"
    },
    {
      "id": "color-67",
      "layer": "color",
      "priority": 2,
      "attribute": "あんず",
      "result": "POP",
      "condition": "他ぽちょに押されて高速化 ＋ 第三者へ衝突 ＋ 相対速度が一定以上 ＋ 弾け補正：相対速度7.8以上",
      "conditionCount": 4,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.8以上"
    },
    {
      "id": "color-68",
      "layer": "color",
      "priority": 2,
      "attribute": "あんず",
      "result": "POP",
      "condition": "同じ相手と連続3回衝突 ＋ 3回目だけ高速 ＋ 一度も接着していない ＋ 弾け補正：相対速度7.8以上",
      "conditionCount": 4,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.8以上"
    },
    {
      "id": "color-69",
      "layer": "color",
      "priority": 2,
      "attribute": "あんず",
      "result": "POP",
      "condition": "天井付近 ＋ 下から高速で飛んできた相手と衝突 ＋ サイズ差が小さい ＋ 弾け補正：相対速度7.8以上",
      "conditionCount": 4,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.8以上"
    },
    {
      "id": "expression-2",
      "layer": "expression",
      "priority": 3,
      "attribute": "ごきげん",
      "result": "STICK",
      "condition": "自分がごきげん ＋ 相手もごきげん ＋ 相対速度が低い ＋ サイズ差が小さい",
      "conditionCount": 4,
      "active": true,
      "status": "active"
    },
    {
      "id": "expression-3",
      "layer": "expression",
      "priority": 3,
      "attribute": "ごきげん",
      "result": "STICK",
      "condition": "自分がごきげん ＋ 相手が異色 ＋ 接触地点が画面上半分 ＋ どちらも直前に壁へ触れていない",
      "conditionCount": 4,
      "active": true,
      "status": "active"
    },
    {
      "id": "expression-4",
      "layer": "expression",
      "priority": 3,
      "attribute": "ごきげん",
      "result": "STICK",
      "condition": "自分がごきげん ＋ 相手と過去に一度接触済み ＋ 今回が再接触 ＋ 接触後の速度が低下する",
      "conditionCount": 4,
      "active": false,
      "status": "unimplemented",
      "missing": "衝突後の速度低下を接触開始時点では正確に判定できない"
    },
    {
      "id": "expression-5",
      "layer": "expression",
      "priority": 3,
      "attribute": "ごきげん",
      "result": "STICK",
      "condition": "自分がごきげん ＋ 相手が単独状態 ＋ 自分も単独状態 ＋ 接触時間が一定以上",
      "conditionCount": 4,
      "active": false,
      "status": "unimplemented",
      "missing": "接触継続時間の計測が未実装"
    },
    {
      "id": "expression-6",
      "layer": "expression",
      "priority": 3,
      "attribute": "ごきげん",
      "result": "STICK",
      "condition": "自分がごきげん ＋ 相手の現在表情がふつう ＋ 相手のサイズが自分と近い ＋ 接触地点の近くに他ぽちょが少ない",
      "conditionCount": 4,
      "active": true,
      "status": "active"
    },
    {
      "id": "expression-7",
      "layer": "expression",
      "priority": 3,
      "attribute": "ごきげん",
      "result": "STICK",
      "condition": "自分がごきげん ＋ 相手と同じ壁に触れた履歴がある ＋ その後初接触 ＋ 相対速度が低い",
      "conditionCount": 4,
      "active": true,
      "status": "active"
    },
    {
      "id": "expression-8",
      "layer": "expression",
      "priority": 3,
      "attribute": "ごきげん",
      "result": "POP",
      "condition": "自分がごきげん ＋ 相手が不機嫌 ＋ 相対速度が高い ＋ 接触地点が壁際 ＋ 弾け補正：相対速度7.4以上",
      "conditionCount": 5,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.4以上"
    },
    {
      "id": "expression-9",
      "layer": "expression",
      "priority": 3,
      "attribute": "ごきげん",
      "result": "POP",
      "condition": "自分がごきげん ＋ 相手もごきげん ＋ 過去に何度も接触済み ＋ 今回だけ高速衝突 ＋ 弾け補正：相対速度7.4以上",
      "conditionCount": 5,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.4以上"
    },
    {
      "id": "expression-10",
      "layer": "expression",
      "priority": 3,
      "attribute": "ごきげん",
      "result": "POP",
      "condition": "自分がごきげん ＋ 天井接触済み ＋ 相手が高速移動中 ＋ サイズ差が大きい ＋ 弾け補正：相対速度7.4以上",
      "conditionCount": 5,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.4以上"
    },
    {
      "id": "expression-11",
      "layer": "expression",
      "priority": 3,
      "attribute": "ごきげん",
      "result": "POP",
      "condition": "自分がごきげん ＋ 一度くっついた相手と再接触 ＋ 前回と表情が異なる ＋ 今回の速度が高い ＋ 弾け補正：相対速度7.4以上",
      "conditionCount": 5,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.4以上"
    },
    {
      "id": "expression-12",
      "layer": "expression",
      "priority": 3,
      "attribute": "ごきげん",
      "result": "POP",
      "condition": "自分がごきげん ＋ 周囲に同色が2体以上いる ＋ 相手が異色 ＋ 正面に近い衝突 ＋ 弾け補正：相対速度7.4以上",
      "conditionCount": 5,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.4以上"
    },
    {
      "id": "expression-13",
      "layer": "expression",
      "priority": 3,
      "attribute": "ふつう",
      "result": "STICK",
      "condition": "自分がふつう ＋ 相手もふつう ＋ 相対速度が低い ＋ どちらも現在単独状態",
      "conditionCount": 4,
      "active": true,
      "status": "active"
    },
    {
      "id": "expression-14",
      "layer": "expression",
      "priority": 3,
      "attribute": "ふつう",
      "result": "STICK",
      "condition": "自分がふつう ＋ 相手がごきげん ＋ 接触後に両者の速度が低下 ＋ サイズ差が一定以下",
      "conditionCount": 4,
      "active": true,
      "status": "active"
    },
    {
      "id": "expression-15",
      "layer": "expression",
      "priority": 3,
      "attribute": "ふつう",
      "result": "STICK",
      "condition": "自分がふつう ＋ 相手が異色 ＋ 過去に接触したことのない色 ＋ 接触地点が画面中央付近",
      "conditionCount": 4,
      "active": true,
      "status": "active"
    },
    {
      "id": "expression-16",
      "layer": "expression",
      "priority": 3,
      "attribute": "ふつう",
      "result": "STICK",
      "condition": "自分がふつう ＋ 壁接触回数が少ない ＋ 相手も壁接触回数が少ない ＋ 低速接触",
      "conditionCount": 4,
      "active": true,
      "status": "active"
    },
    {
      "id": "expression-17",
      "layer": "expression",
      "priority": 3,
      "attribute": "ふつう",
      "result": "STICK",
      "condition": "自分がふつう ＋ 相手と接触する直前までしばらく単独 ＋ 相手も単独 ＋ 今回が初接触",
      "conditionCount": 4,
      "active": true,
      "status": "active"
    },
    {
      "id": "expression-18",
      "layer": "expression",
      "priority": 3,
      "attribute": "ふつう",
      "result": "STICK",
      "condition": "自分がふつう ＋ 接触地点近くに他ぽちょが2体以下 ＋ 相手が停止に近い ＋ 自分の速度も低い",
      "conditionCount": 4,
      "active": true,
      "status": "active"
    },
    {
      "id": "expression-19",
      "layer": "expression",
      "priority": 3,
      "attribute": "ふつう",
      "result": "POP",
      "condition": "自分がふつう ＋ 相手が不機嫌 ＋ 相対速度が高い ＋ 接触地点が天井付近 ＋ 弾け補正：相対速度7.4以上",
      "conditionCount": 5,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.4以上"
    },
    {
      "id": "expression-20",
      "layer": "expression",
      "priority": 3,
      "attribute": "ふつう",
      "result": "POP",
      "condition": "自分がふつう ＋ 相手もふつう ＋ 両者とも高速移動中 ＋ サイズ差が小さい ＋ 弾け補正：相対速度7.4以上",
      "conditionCount": 5,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.4以上"
    },
    {
      "id": "expression-21",
      "layer": "expression",
      "priority": 3,
      "attribute": "ふつう",
      "result": "POP",
      "condition": "自分がふつう ＋ 過去に同じ相手と複数回接触済み ＋ 一度もくっついていない ＋ 今回が高速 ＋ 弾け補正：相対速度7.4以上",
      "conditionCount": 5,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.4以上"
    },
    {
      "id": "expression-22",
      "layer": "expression",
      "priority": 3,
      "attribute": "ふつう",
      "result": "POP",
      "condition": "自分がふつう ＋ 壁接触直後 ＋ 異色相手 ＋ 接触角度が正面寄り ＋ 弾け補正：相対速度7.4以上",
      "conditionCount": 5,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.4以上"
    },
    {
      "id": "expression-23",
      "layer": "expression",
      "priority": 3,
      "attribute": "ふつう",
      "result": "POP",
      "condition": "自分がふつう ＋ 接触地点周辺に複数のぽちょがいる ＋ 相手が移動中 ＋ 自分も移動中 ＋ 弾け補正：相対速度7.4以上",
      "conditionCount": 5,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.4以上"
    },
    {
      "id": "expression-24",
      "layer": "expression",
      "priority": 3,
      "attribute": "ふつう",
      "result": "POP",
      "condition": "自分がふつう ＋ 過去に表情変化済み ＋ 変化後初めての高速衝突 ＋ 相手が異色 ＋ 弾け補正：相対速度7.4以上",
      "conditionCount": 5,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.4以上"
    },
    {
      "id": "expression-25",
      "layer": "expression",
      "priority": 3,
      "attribute": "不機嫌",
      "result": "STICK",
      "condition": "自分が不機嫌 ＋ 相手も不機嫌 ＋ 相対速度が低い ＋ 過去に一度以上接触済み",
      "conditionCount": 4,
      "active": true,
      "status": "active"
    },
    {
      "id": "expression-26",
      "layer": "expression",
      "priority": 3,
      "attribute": "不機嫌",
      "result": "STICK",
      "condition": "自分が不機嫌 ＋ 相手がふつう ＋ 接触地点が壁際 ＋ 接触後に両者がほぼ停止",
      "conditionCount": 4,
      "active": true,
      "status": "active"
    },
    {
      "id": "expression-27",
      "layer": "expression",
      "priority": 3,
      "attribute": "不機嫌",
      "result": "STICK",
      "condition": "自分が不機嫌 ＋ 一度別れた相手と再接触 ＋ 今回の速度が低い ＋ サイズ差が小さい",
      "conditionCount": 4,
      "active": true,
      "status": "active"
    },
    {
      "id": "expression-28",
      "layer": "expression",
      "priority": 3,
      "attribute": "不機嫌",
      "result": "STICK",
      "condition": "自分が不機嫌 ＋ 相手が同色 ＋ 過去の接触回数が多い ＋ 今回が低速",
      "conditionCount": 4,
      "active": true,
      "status": "active"
    },
    {
      "id": "expression-29",
      "layer": "expression",
      "priority": 3,
      "attribute": "不機嫌",
      "result": "STICK",
      "condition": "自分が不機嫌 ＋ 周囲に同表情が2体以上いる ＋ 相手が単独状態 ＋ 接触時間が一定以上",
      "conditionCount": 4,
      "active": false,
      "status": "unimplemented",
      "missing": "接触継続時間の計測が未実装"
    },
    {
      "id": "expression-30",
      "layer": "expression",
      "priority": 3,
      "attribute": "不機嫌",
      "result": "POP",
      "condition": "自分が不機嫌 ＋ 相手も不機嫌 ＋ 相対速度が高い ＋ 正面に近い衝突 ＋ 弾け補正：相対速度7.4以上",
      "conditionCount": 5,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.4以上"
    },
    {
      "id": "expression-31",
      "layer": "expression",
      "priority": 3,
      "attribute": "不機嫌",
      "result": "POP",
      "condition": "自分が不機嫌 ＋ 相手がごきげん ＋ 接触地点が画面上半分 ＋ サイズ差が大きい ＋ 弾け補正：相対速度7.4以上",
      "conditionCount": 5,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.4以上"
    },
    {
      "id": "expression-32",
      "layer": "expression",
      "priority": 3,
      "attribute": "不機嫌",
      "result": "POP",
      "condition": "自分が不機嫌 ＋ 壁接触回数が一定以上 ＋ 異色相手 ＋ 高速衝突 ＋ 弾け補正：相対速度7.4以上",
      "conditionCount": 5,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.4以上"
    },
    {
      "id": "expression-33",
      "layer": "expression",
      "priority": 3,
      "attribute": "不機嫌",
      "result": "POP",
      "condition": "自分が不機嫌 ＋ 一度くっついた相手と再接触 ＋ 前回より高い速度 ＋ 相手の表情が変化済み ＋ 弾け補正：相対速度7.4以上",
      "conditionCount": 5,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.4以上"
    },
    {
      "id": "expression-34",
      "layer": "expression",
      "priority": 3,
      "attribute": "不機嫌",
      "result": "POP",
      "condition": "自分が不機嫌 ＋ 天井接触直後 ＋ 相手が下方向に動いている ＋ 相対速度が高い ＋ 弾け補正：相対速度7.4以上",
      "conditionCount": 5,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.4以上"
    },
    {
      "id": "expression-35",
      "layer": "expression",
      "priority": 3,
      "attribute": "不機嫌",
      "result": "POP",
      "condition": "自分が不機嫌 ＋ 周囲に他ぽちょが多い ＋ 接触地点が密集地帯 ＋ 衝突後に誰かを押す ＋ 弾け補正：相対速度7.4以上",
      "conditionCount": 5,
      "active": false,
      "status": "unimplemented",
      "missing": "衝突後に第三者を押したかの事後判定が未実装",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.4以上"
    },
    {
      "id": "expression-36",
      "layer": "expression",
      "priority": 3,
      "attribute": "不機嫌",
      "result": "POP",
      "condition": "自分が不機嫌 ＋ 相手と連続接触中 ＋ 今回だけ速度が急上昇 ＋ 一度もくっついていない ＋ 弾け補正：相対速度7.4以上",
      "conditionCount": 5,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.4以上"
    },
    {
      "id": "decoration-2",
      "layer": "decoration",
      "priority": 4,
      "attribute": "リボン",
      "result": "STICK",
      "condition": "リボン付き ＋ 相手と過去に接触済み ＋ 一度離れている ＋ 今回が低速 ＋ サイズ差が小さい",
      "conditionCount": 5,
      "active": true,
      "status": "active"
    },
    {
      "id": "decoration-3",
      "layer": "decoration",
      "priority": 4,
      "attribute": "リボン",
      "result": "STICK",
      "condition": "リボン付き ＋ 相手も装飾あり ＋ 装飾種類が異なる ＋ 双方単独 ＋ 画面上半分 ＋ 低速接触",
      "conditionCount": 6,
      "active": true,
      "status": "active"
    },
    {
      "id": "decoration-4",
      "layer": "decoration",
      "priority": 4,
      "attribute": "リボン",
      "result": "STICK",
      "condition": "リボン付き ＋ 過去に同じグループだった相手 ＋ 現在表情が前回接着時と同じ ＋ 再接触 ＋ 相対速度が低い",
      "conditionCount": 5,
      "active": true,
      "status": "active"
    },
    {
      "id": "decoration-5",
      "layer": "decoration",
      "priority": 4,
      "attribute": "リボン",
      "result": "STICK",
      "condition": "リボン付き ＋ 相手がごきげん ＋ 自分が異色 ＋ 接触前に一定時間誰とも触れていない ＋ 接触時間が一定以上",
      "conditionCount": 5,
      "active": false,
      "status": "unimplemented",
      "missing": "接触継続時間の計測が未実装"
    },
    {
      "id": "decoration-6",
      "layer": "decoration",
      "priority": 4,
      "attribute": "リボン",
      "result": "STICK",
      "condition": "リボン付き ＋ 接触相手が直前に別ぽちょと離れている ＋ 自分は単独 ＋ 相手より小さい ＋ 低速 ＋ 壁際ではない",
      "conditionCount": 6,
      "active": true,
      "status": "active"
    },
    {
      "id": "decoration-7",
      "layer": "decoration",
      "priority": 4,
      "attribute": "リボン",
      "result": "STICK",
      "condition": "リボン付き ＋ 同じ相手への接触3回目以上 ＋ 一度も弾け条件未成立 ＋ 双方高速ではない ＋ 周囲に他ぽちょが少ない",
      "conditionCount": 5,
      "active": true,
      "status": "active"
    },
    {
      "id": "decoration-8",
      "layer": "decoration",
      "priority": 4,
      "attribute": "リボン",
      "result": "POP",
      "condition": "リボン付き ＋ 一度くっついた相手 ＋ 再接触 ＋ 前回と表情が違う ＋ 今回が高速 ＋ 弾け補正：相対速度7.0以上",
      "conditionCount": 6,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.0以上"
    },
    {
      "id": "decoration-9",
      "layer": "decoration",
      "priority": 4,
      "attribute": "リボン",
      "result": "POP",
      "condition": "リボン付き ＋ 同じ相手と短時間に複数回接触 ＋ 一度もくっついていない ＋ 異色 ＋ 壁際 ＋ 高速 ＋ 弾け補正：相対速度7.0以上",
      "conditionCount": 7,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.0以上"
    },
    {
      "id": "decoration-10",
      "layer": "decoration",
      "priority": 4,
      "attribute": "リボン",
      "result": "POP",
      "condition": "リボン付き ＋ 自分がごきげん ＋ 相手が不機嫌 ＋ 過去に接触済み ＋ サイズ差が大きい ＋ 高速 ＋ 弾け補正：相対速度7.0以上",
      "conditionCount": 7,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.0以上"
    },
    {
      "id": "decoration-11",
      "layer": "decoration",
      "priority": 4,
      "attribute": "リボン",
      "result": "POP",
      "condition": "リボン付き ＋ 長時間接着していた履歴あり ＋ 現在単独 ＋ 別の相手へ初接触 ＋ 相手が高速 ＋ 天井付近 ＋ 弾け補正：相対速度7.0以上",
      "conditionCount": 7,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.0以上"
    },
    {
      "id": "decoration-12",
      "layer": "decoration",
      "priority": 4,
      "attribute": "メガネ",
      "result": "STICK",
      "condition": "メガネ付き ＋ 総接触回数が偶数 ＋ 今回が初対面 ＋ 相手が異色 ＋ 接触速度が低い",
      "conditionCount": 5,
      "active": true,
      "status": "active"
    },
    {
      "id": "decoration-13",
      "layer": "decoration",
      "priority": 4,
      "attribute": "メガネ",
      "result": "STICK",
      "condition": "メガネ付き ＋ 直近3回の接触相手がすべて異なる ＋ 今回が過去接触済み相手 ＋ 低速 ＋ 画面中央付近",
      "conditionCount": 5,
      "active": true,
      "status": "active"
    },
    {
      "id": "decoration-14",
      "layer": "decoration",
      "priority": 4,
      "attribute": "メガネ",
      "result": "STICK",
      "condition": "メガネ付き ＋ 壁接触回数が3回以上 ＋ 左右両壁に接触済み ＋ 相手が停止に近い ＋ サイズ差が小さい",
      "conditionCount": 5,
      "active": true,
      "status": "active"
    },
    {
      "id": "decoration-15",
      "layer": "decoration",
      "priority": 4,
      "attribute": "メガネ",
      "result": "STICK",
      "condition": "メガネ付き ＋ 射出順が相手より後 ＋ 射出順の差が偶数 ＋ 双方天井接触済み ＋ 相対速度が低い",
      "conditionCount": 5,
      "active": true,
      "status": "active"
    },
    {
      "id": "decoration-16",
      "layer": "decoration",
      "priority": 4,
      "attribute": "メガネ",
      "result": "STICK",
      "condition": "メガネ付き ＋ 同色接触回数より異色接触回数が多い ＋ 相手が同色 ＋ 今回が低速 ＋ 双方単独",
      "conditionCount": 5,
      "active": true,
      "status": "active"
    },
    {
      "id": "decoration-17",
      "layer": "decoration",
      "priority": 4,
      "attribute": "メガネ",
      "result": "STICK",
      "condition": "メガネ付き ＋ 直前の接触で何も起きていない ＋ 今回が別相手 ＋ 相手がふつう表情 ＋ サイズ差が小さい ＋ 低速",
      "conditionCount": 6,
      "active": true,
      "status": "active"
    },
    {
      "id": "decoration-18",
      "layer": "decoration",
      "priority": 4,
      "attribute": "メガネ",
      "result": "POP",
      "condition": "メガネ付き ＋ 総接触回数が5回以上 ＋ 今回が同じ相手との3回目以上 ＋ 高速 ＋ 相手が異色 ＋ 弾け補正：相対速度7.0以上",
      "conditionCount": 6,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.0以上"
    },
    {
      "id": "decoration-19",
      "layer": "decoration",
      "priority": 4,
      "attribute": "メガネ",
      "result": "POP",
      "condition": "メガネ付き ＋ 壁接触回数が3の倍数 ＋ 天井接触済み ＋ 初対面相手 ＋ 高速 ＋ 弾け補正：相対速度7.0以上",
      "conditionCount": 6,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.0以上"
    },
    {
      "id": "decoration-20",
      "layer": "decoration",
      "priority": 4,
      "attribute": "メガネ",
      "result": "POP",
      "condition": "メガネ付き ＋ 直近の接触色が3種類すべて異なる ＋ 今回がそのどれかと同色 ＋ 高速 ＋ 画面上半分 ＋ 弾け補正：相対速度7.0以上",
      "conditionCount": 6,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.0以上"
    },
    {
      "id": "decoration-21",
      "layer": "decoration",
      "priority": 4,
      "attribute": "メガネ",
      "result": "POP",
      "condition": "メガネ付き ＋ 射出から一定時間経過 ＋ 一度も接着していない ＋ 接触回数が一定以上 ＋ 相手もメガネなし ＋ 高速 ＋ 弾け補正：相対速度7.0以上",
      "conditionCount": 7,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.0以上"
    },
    {
      "id": "decoration-22",
      "layer": "decoration",
      "priority": 4,
      "attribute": "メガネ",
      "result": "POP",
      "condition": "メガネ付き ＋ 直前イベントが「離れる」 ＋ 一定時間以内 ＋ 別グループへ衝突 ＋ サイズ差が大きい ＋ 高速 ＋ 弾け補正：相対速度7.0以上",
      "conditionCount": 7,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.0以上"
    },
    {
      "id": "decoration-23",
      "layer": "decoration",
      "priority": 4,
      "attribute": "王冠",
      "result": "STICK",
      "condition": "王冠付き ＋ 接触相手より自分が大きい ＋ 周囲に自分より大きいぽちょがいない ＋ 相手が単独 ＋ 低速",
      "conditionCount": 5,
      "active": true,
      "status": "active"
    },
    {
      "id": "decoration-24",
      "layer": "decoration",
      "priority": 4,
      "attribute": "王冠",
      "result": "STICK",
      "condition": "王冠付き ＋ 自分が周辺で最大サイズ ＋ 相手が装飾なし ＋ 相手が自分より小さい ＋ 画面上半分 ＋ 低速",
      "conditionCount": 6,
      "active": true,
      "status": "active"
    },
    {
      "id": "decoration-25",
      "layer": "decoration",
      "priority": 4,
      "attribute": "王冠",
      "result": "STICK",
      "condition": "王冠付き ＋ 現在グループに属していない ＋ 相手が2体以上のグループ所属 ＋ グループ内に王冠なし ＋ 接触速度が低い ＋ 自分が異色",
      "conditionCount": 6,
      "active": true,
      "status": "active"
    },
    {
      "id": "decoration-26",
      "layer": "decoration",
      "priority": 4,
      "attribute": "王冠",
      "result": "STICK",
      "condition": "王冠付き ＋ 周囲に3体以上 ＋ その中で自分だけ装飾あり ＋ 相手がふつう ＋ サイズ差が一定以下 ＋ 低速",
      "conditionCount": 6,
      "active": true,
      "status": "active"
    },
    {
      "id": "decoration-27",
      "layer": "decoration",
      "priority": 4,
      "attribute": "王冠",
      "result": "STICK",
      "condition": "王冠付き ＋ 過去に最大4体以上のグループへ所属 ＋ 現在単独 ＋ 新しいグループへ接触 ＋ 自分がその中で最大 ＋ 低速",
      "conditionCount": 6,
      "active": true,
      "status": "active"
    },
    {
      "id": "decoration-28",
      "layer": "decoration",
      "priority": 4,
      "attribute": "王冠",
      "result": "STICK",
      "condition": "王冠付き ＋ 相手も王冠 ＋ 双方単独 ＋ サイズ差が非常に小さい ＋ どちらも低速 ＋ 壁際ではない",
      "conditionCount": 6,
      "active": true,
      "status": "active"
    },
    {
      "id": "decoration-29",
      "layer": "decoration",
      "priority": 4,
      "attribute": "王冠",
      "result": "POP",
      "condition": "王冠付き ＋ 自分が周辺最大サイズ ＋ 相手も大サイズ ＋ 高速正面衝突 ＋ 周囲に他ぽちょが2体以上 ＋ 弾け補正：相対速度7.0以上",
      "conditionCount": 6,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.0以上"
    },
    {
      "id": "decoration-30",
      "layer": "decoration",
      "priority": 4,
      "attribute": "王冠",
      "result": "POP",
      "condition": "王冠付き ＋ 相手も王冠 ＋ サイズ差が大きい ＋ 小さい方が高速 ＋ 天井付近 ＋ 弾け補正：相対速度7.0以上",
      "conditionCount": 6,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.0以上"
    },
    {
      "id": "decoration-31",
      "layer": "decoration",
      "priority": 4,
      "attribute": "王冠",
      "result": "POP",
      "condition": "王冠付き ＋ 自分がグループ内最大 ＋ グループ人数4体以上 ＋ 外部から高速衝突を受ける ＋ 衝突相手が異色 ＋ 弾け補正：相対速度7.0以上",
      "conditionCount": 6,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.0以上"
    },
    {
      "id": "decoration-32",
      "layer": "decoration",
      "priority": 4,
      "attribute": "王冠",
      "result": "POP",
      "condition": "王冠付き ＋ 周囲に装飾付きが2体以上 ＋ 自分だけ表情が異なる ＋ 高速接触 ＋ 壁際 ＋ 弾け補正：相対速度7.0以上",
      "conditionCount": 6,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.0以上"
    },
    {
      "id": "decoration-33",
      "layer": "decoration",
      "priority": 4,
      "attribute": "王冠",
      "result": "POP",
      "condition": "王冠付き ＋ 一度グループの中心付近にいた ＋ 現在端にいる ＋ 外部ぽちょに衝突 ＋ 相手が自分より大きい ＋ 高速 ＋ 弾け補正：相対速度7.0以上",
      "conditionCount": 7,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.0以上"
    },
    {
      "id": "decoration-34",
      "layer": "decoration",
      "priority": 4,
      "attribute": "芽",
      "result": "STICK",
      "condition": "芽付き ＋ 生存時間が一定以上 ＋ 一度も接着していない ＋ 相手が初対面 ＋ 低速",
      "conditionCount": 5,
      "active": true,
      "status": "active"
    },
    {
      "id": "decoration-35",
      "layer": "decoration",
      "priority": 4,
      "attribute": "芽",
      "result": "STICK",
      "condition": "芽付き ＋ 表情変化経験あり ＋ 変化後一定時間経過 ＋ 相手が異色 ＋ 接触速度が低い",
      "conditionCount": 5,
      "active": true,
      "status": "active"
    },
    {
      "id": "decoration-36",
      "layer": "decoration",
      "priority": 4,
      "attribute": "芽",
      "result": "STICK",
      "condition": "芽付き ＋ 長時間単独だった ＋ 相手がグループ所属 ＋ グループ内に芽付きなし ＋ 自分が小サイズ ＋ 低速",
      "conditionCount": 6,
      "active": true,
      "status": "active"
    },
    {
      "id": "decoration-37",
      "layer": "decoration",
      "priority": 4,
      "attribute": "芽",
      "result": "STICK",
      "condition": "芽付き ＋ 生存中に3色以上へ接触済み ＋ 今回が未接触色 ＋ 双方低速 ＋ 天井付近",
      "conditionCount": 5,
      "active": true,
      "status": "active"
    },
    {
      "id": "decoration-38",
      "layer": "decoration",
      "priority": 4,
      "attribute": "芽",
      "result": "STICK",
      "condition": "芽付き ＋ 一度くっついて離れた ＋ その後誰とも接触していない ＋ 新しい相手 ＋ サイズ差が小さい ＋ 低速",
      "conditionCount": 6,
      "active": true,
      "status": "active"
    },
    {
      "id": "decoration-39",
      "layer": "decoration",
      "priority": 4,
      "attribute": "芽",
      "result": "STICK",
      "condition": "芽付き ＋ 天井付近に一定時間滞在 ＋ 相手も長時間生存 ＋ 相手が装飾なし ＋ 相対速度が低い ＋ 周囲が密集していない",
      "conditionCount": 6,
      "active": true,
      "status": "active"
    },
    {
      "id": "decoration-40",
      "layer": "decoration",
      "priority": 4,
      "attribute": "芽",
      "result": "POP",
      "condition": "芽付き ＋ 長時間生存 ＋ 総接触回数が多い ＋ 相手が高速 ＋ 自分が低速 ＋ 弾け補正：相対速度7.0以上",
      "conditionCount": 6,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.0以上"
    },
    {
      "id": "decoration-41",
      "layer": "decoration",
      "priority": 4,
      "attribute": "芽",
      "result": "POP",
      "condition": "芽付き ＋ 表情変化2回以上 ＋ 過去に接着経験あり ＋ 現在単独 ＋ 異色相手へ高速接触 ＋ 弾け補正：相対速度7.0以上",
      "conditionCount": 6,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.0以上"
    },
    {
      "id": "decoration-42",
      "layer": "decoration",
      "priority": 4,
      "attribute": "芽",
      "result": "POP",
      "condition": "芽付き ＋ 生存中に全基本色へ接触済み ＋ 今回が同色 ＋ 高速 ＋ 天井付近 ＋ 弾け補正：相対速度7.0以上",
      "conditionCount": 6,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.0以上"
    },
    {
      "id": "decoration-43",
      "layer": "decoration",
      "priority": 4,
      "attribute": "芽",
      "result": "POP",
      "condition": "芽付き ＋ 長時間静止状態を経験 ＋ その後初めての高速移動 ＋ 他ぽちょへ衝突 ＋ サイズ差が大きい ＋ 弾け補正：相対速度7.0以上",
      "conditionCount": 6,
      "active": false,
      "status": "unimplemented",
      "missing": "長時間静止後の「初めての高速移動」履歴が未実装",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.0以上"
    },
    {
      "id": "decoration-44",
      "layer": "decoration",
      "priority": 4,
      "attribute": "芽",
      "result": "POP",
      "condition": "芽付き ＋ 過去に3体以上を誘爆で見送っている ＋ 自分は一度も誘爆されていない ＋ 新しいグループへ接触 ＋ 高速 ＋ 弾け補正：相対速度7.0以上",
      "conditionCount": 6,
      "active": true,
      "status": "active",
      "burstTuning": "v0.1.3: 弾け補正：相対速度7.0以上"
    },
    {
      "id": "special-2",
      "layer": "special",
      "priority": 5,
      "attribute": "さくら×リボン",
      "result": "STICK",
      "condition": "さくら ＋ リボン ＋ 相手と過去に接触済み ＋ 今回が低速接触",
      "conditionCount": 4,
      "active": true,
      "status": "active"
    },
    {
      "id": "special-3",
      "layer": "special",
      "priority": 5,
      "attribute": "みずいろ×メガネ",
      "result": "STICK",
      "condition": "みずいろ ＋ メガネ ＋ 壁に2回以上当たっている ＋ 今回が低速接触",
      "conditionCount": 4,
      "active": true,
      "status": "active"
    },
    {
      "id": "special-4",
      "layer": "special",
      "priority": 5,
      "attribute": "あんず×不機嫌",
      "result": "POP",
      "condition": "あんず ＋ 不機嫌 ＋ 相対速度が高い ＋ 正面に近い衝突",
      "conditionCount": 4,
      "active": true,
      "status": "active"
    },
    {
      "id": "special-5",
      "layer": "special",
      "priority": 5,
      "attribute": "わかば×芽",
      "result": "STICK",
      "condition": "わかば ＋ 芽 ＋ 生存時間が一定以上 ＋ 今回が低速接触",
      "conditionCount": 4,
      "active": true,
      "status": "active"
    },
    {
      "id": "special-6",
      "layer": "special",
      "priority": 5,
      "attribute": "ふじ×王冠",
      "result": "POP",
      "condition": "ふじ ＋ 王冠 ＋ 周囲に3体以上いる ＋ 今回が高速接触",
      "conditionCount": 4,
      "active": true,
      "status": "active"
    },
    {
      "id": "special-7",
      "layer": "special",
      "priority": 5,
      "attribute": "たまご×ふつう",
      "result": "STICK",
      "condition": "たまご ＋ ふつう ＋ 同じ相手との接触が3回目 ＋ 今回が低速",
      "conditionCount": 4,
      "active": true,
      "status": "active"
    },
    {
      "id": "special-8",
      "layer": "special",
      "priority": 5,
      "attribute": "さくら×ごきげん×リボン",
      "result": "STICK",
      "condition": "さくら ＋ ごきげん ＋ リボン ＋ 相手と一度離れた履歴あり",
      "conditionCount": 4,
      "active": true,
      "status": "active"
    },
    {
      "id": "special-9",
      "layer": "special",
      "priority": 5,
      "attribute": "みずいろ×不機嫌×メガネ",
      "result": "POP",
      "condition": "みずいろ ＋ 不機嫌 ＋ メガネ ＋ 天井接触済み ＋ 今回が高速接触",
      "conditionCount": 5,
      "active": true,
      "status": "active"
    },
    {
      "id": "special-10",
      "layer": "special",
      "priority": 5,
      "attribute": "あんず×ごきげん×小",
      "result": "POP",
      "condition": "あんず ＋ ごきげん ＋ 小 ＋ 相手が大 ＋ 自分からぶつかる",
      "conditionCount": 5,
      "active": true,
      "status": "active"
    },
    {
      "id": "special-11",
      "layer": "special",
      "priority": 5,
      "attribute": "ふじ×不機嫌×王冠",
      "result": "POP",
      "condition": "ふじ ＋ 不機嫌 ＋ 王冠 ＋ 周囲に異色が3色以上いる",
      "conditionCount": 4,
      "active": true,
      "status": "active"
    },
    {
      "id": "special-12",
      "layer": "special",
      "priority": 5,
      "attribute": "わかば×ふつう×芽",
      "result": "STICK",
      "condition": "わかば ＋ ふつう ＋ 芽 ＋ 長時間単独だった ＋ 今回が初対面相手",
      "conditionCount": 5,
      "active": true,
      "status": "active"
    },
    {
      "id": "special-13",
      "layer": "special",
      "priority": 5,
      "attribute": "さくら×不機嫌×リボン×小",
      "result": "POP",
      "condition": "さくら ＋ 不機嫌 ＋ リボン ＋ 小 ＋ 一度くっついた相手との再接触",
      "conditionCount": 5,
      "active": true,
      "status": "active"
    },
    {
      "id": "special-14",
      "layer": "special",
      "priority": 5,
      "attribute": "たまご×ごきげん×メガネ×中",
      "result": "STICK",
      "condition": "たまご ＋ ごきげん ＋ メガネ ＋ 中 ＋ 総接触回数が5回以上",
      "conditionCount": 5,
      "active": true,
      "status": "active"
    },
    {
      "id": "special-15",
      "layer": "special",
      "priority": 5,
      "attribute": "みずいろ×ふつう×王冠×大",
      "result": "POP",
      "condition": "みずいろ ＋ ふつう ＋ 王冠 ＋ 大 ＋ 壁反射直後 ＋ 今回が高速接触",
      "conditionCount": 6,
      "active": true,
      "status": "active"
    },
    {
      "id": "special-16",
      "layer": "special",
      "priority": 5,
      "attribute": "ふじ×ごきげん×芽×小",
      "result": "STICK",
      "condition": "ふじ ＋ ごきげん ＋ 芽 ＋ 小 ＋ 周囲に2色以上いる ＋ 今回が低速接触",
      "conditionCount": 6,
      "active": true,
      "status": "active"
    },
    {
      "id": "special-17",
      "layer": "special",
      "priority": 5,
      "attribute": "あんず×不機嫌×王冠×大",
      "result": "POP",
      "condition": "あんず ＋ 不機嫌 ＋ 王冠 ＋ 大 ＋ 相手も大 ＋ 正面衝突",
      "conditionCount": 6,
      "active": true,
      "status": "active"
    }
  ],
  "roles": [
    {
      "id": 1,
      "rarity": 1,
      "name": "なかよし",
      "trigger": "くっつく",
      "score": 120,
      "andCount": 2,
      "condition": "同色 ＋ 同じ表情",
      "undiscovered": "似ているだけで、うまくいくとは限らない。",
      "discovered": "今回は、うまくいった。",
      "audit": "成立可能",
      "active": true
    },
    {
      "id": 2,
      "rarity": 1,
      "name": "凸凹コンビ",
      "trigger": "くっつく",
      "score": 140,
      "andCount": 2,
      "condition": "サイズが小と大 ＋ 異色",
      "undiscovered": "違いは案外、邪魔にならない。",
      "discovered": "ちょうど足りないところが噛み合った。",
      "audit": "成立可能",
      "active": true
    },
    {
      "id": 3,
      "rarity": 1,
      "name": "意気投合",
      "trigger": "くっつく",
      "score": 180,
      "andCount": 3,
      "condition": "初対面 ＋ 同じ表情 ＋ 低速接触",
      "undiscovered": "初対面でも話が早いことはある。",
      "discovered": "話が早かった。",
      "audit": "成立可能",
      "active": true
    },
    {
      "id": 4,
      "rarity": 1,
      "name": "おしくらぽちょ",
      "trigger": "くっつく",
      "score": 130,
      "andCount": 2,
      "condition": "接触地点付近に他ぽちょが2体以上 ＋ 画面上半分",
      "undiscovered": "狭いところほど距離は縮まる。",
      "discovered": "押されるうちに仲間になった。",
      "audit": "成立可能",
      "active": true
    },
    {
      "id": 5,
      "rarity": 1,
      "name": "壁友",
      "trigger": "くっつく",
      "score": 150,
      "andCount": 2,
      "condition": "両方とも壁接触経験あり ＋ 同じ種類の壁に触れたことがある",
      "undiscovered": "同じ場所を知っているだけで話題はできる。",
      "discovered": "共通の壁があった。",
      "audit": "成立可能",
      "active": true
    },
    {
      "id": 6,
      "rarity": 1,
      "name": "ぽちょ先輩",
      "trigger": "くっつく",
      "score": 160,
      "andCount": 2,
      "condition": "片方がもう片方より5発以上前に射出 ＋ 古い方が大きい",
      "undiscovered": "先にいる方が偉いとは限らない。",
      "discovered": "一応、先輩だった。",
      "audit": "成立可能",
      "active": true
    },
    {
      "id": 7,
      "rarity": 1,
      "name": "初対面です",
      "trigger": "何も起こらない",
      "score": 90,
      "andCount": 3,
      "condition": "初接触 ＋ 異色 ＋ 異表情",
      "undiscovered": "初対面なら、こういうこともある。",
      "discovered": "本当に初対面だった。",
      "audit": "成立可能",
      "active": true
    },
    {
      "id": 8,
      "rarity": 1,
      "name": "微妙な距離感",
      "trigger": "何も起こらない",
      "score": 110,
      "andCount": 2,
      "condition": "過去に1回以上接触済み ＋ 一度もくっついていない",
      "undiscovered": "会ったことがあるからといって。",
      "discovered": "まだその距離だった。",
      "audit": "成立可能",
      "active": true
    },
    {
      "id": 9,
      "rarity": 1,
      "name": "すれ違い",
      "trigger": "何も起こらない",
      "score": 100,
      "andCount": 2,
      "condition": "相対速度が高い ＋ 接触時間が短い",
      "undiscovered": "速すぎると何も残らない。",
      "discovered": "本当に一瞬だった。",
      "audit": "未実装：接触終了判定",
      "active": false,
      "missing": "接触継続時間の計測が未実装"
    },
    {
      "id": 10,
      "rarity": 1,
      "name": "その顔で？",
      "trigger": "何も起こらない",
      "score": 130,
      "andCount": 2,
      "condition": "両方ごきげん ＋ 高速衝突",
      "undiscovered": "表情と行動は別問題。",
      "discovered": "楽しそうではあった。",
      "audit": "成立可能",
      "active": true
    },
    {
      "id": 11,
      "rarity": 1,
      "name": "大当たり",
      "trigger": "弾ける",
      "score": 150,
      "andCount": 2,
      "condition": "起爆ぽちょが大サイズ ＋ 高速衝突が原因",
      "undiscovered": "大きいものほど目立つ。",
      "discovered": "かなり大きく当たった。",
      "audit": "成立可能",
      "active": true
    },
    {
      "id": 12,
      "rarity": 1,
      "name": "小さな爆発",
      "trigger": "弾ける",
      "score": 120,
      "andCount": 2,
      "condition": "起爆ぽちょが小サイズ ＋ 誘爆なし",
      "undiscovered": "小さくても、なくなる時はなくなる。",
      "discovered": "ひとりで静かに弾けた。",
      "audit": "成立可能",
      "active": true
    },
    {
      "id": 13,
      "rarity": 1,
      "name": "道連れ",
      "trigger": "弾ける",
      "score": 180,
      "andCount": 2,
      "condition": "誘爆1体以上 ＋ 起爆ぽちょと誘爆ぽちょが異色",
      "undiscovered": "ひとりで済むとは限らない。",
      "discovered": "別の色まで連れていった。",
      "audit": "成立可能",
      "active": true
    },
    {
      "id": 14,
      "rarity": 1,
      "name": "最期まで笑顔",
      "trigger": "弾ける",
      "score": 130,
      "andCount": 2,
      "condition": "起爆ぽちょがごきげん ＋ 表情変化経験なし",
      "undiscovered": "最後まで変わらないものもある。",
      "discovered": "最後まで笑っていた。",
      "audit": "成立可能",
      "active": true
    },
    {
      "id": 15,
      "rarity": 1,
      "name": "天井暮らし",
      "trigger": "弾ける",
      "score": 140,
      "andCount": 2,
      "condition": "起爆ぽちょが天井接触済み ＋ 画面上部で弾ける",
      "undiscovered": "上の方は案外にぎやかだ。",
      "discovered": "天井生活は長くなかった。",
      "audit": "成立可能",
      "active": true
    },
    {
      "id": 16,
      "rarity": 2,
      "name": "またお前か",
      "trigger": "何も起こらない",
      "score": 280,
      "andCount": 3,
      "condition": "同じ相手との3回目以上の接触 ＋ 一度も接着していない ＋ 同じ表情",
      "undiscovered": "世間は狭い。",
      "discovered": "本当にまたいた。",
      "audit": "成立可能",
      "active": true
    },
    {
      "id": 17,
      "rarity": 2,
      "name": "気が合うね",
      "trigger": "くっつく",
      "score": 320,
      "andCount": 4,
      "condition": "異色 ＋ 同表情 ＋ サイズ区分も同じ ＋ 初接触",
      "undiscovered": "違っていても、同じところはある。",
      "discovered": "初対面にしては気が合った。",
      "audit": "成立可能",
      "active": true
    },
    {
      "id": 18,
      "rarity": 2,
      "name": "昔から知ってます",
      "trigger": "くっつく",
      "score": 360,
      "andCount": 4,
      "condition": "過去に2回以上接触 ＋ 一度離れて一定時間経過 ＋ 再接触 ＋ 低速",
      "undiscovered": "時間が空いても忘れないことがある。",
      "discovered": "久しぶりでも話は通じた。",
      "audit": "成立可能",
      "active": true
    },
    {
      "id": 19,
      "rarity": 2,
      "name": "隅っこ会議",
      "trigger": "くっつく",
      "score": 420,
      "andCount": 4,
      "condition": "画面の角付近 ＋ 3体以上の接着グループになる ＋ 3体のうち2色以上 ＋ 全員高速ではない",
      "undiscovered": "広い場所が好きとは限らない。",
      "discovered": "角で話がまとまった。",
      "audit": "成立可能",
      "active": true
    },
    {
      "id": 20,
      "rarity": 2,
      "name": "新入り",
      "trigger": "くっつく",
      "score": 390,
      "andCount": 4,
      "condition": "3体以上の既存グループへ加入 ＋ 加入者が単独だった ＋ 加入者が異色 ＋ 低速接触",
      "undiscovered": "入る場所があるなら入ってみてもいい。",
      "discovered": "新入りを受け入れた。",
      "audit": "成立可能",
      "active": true
    },
    {
      "id": 21,
      "rarity": 2,
      "name": "おそろいじゃない",
      "trigger": "くっつく",
      "score": 410,
      "andCount": 4,
      "condition": "両方装飾あり ＋ 装飾種類が異なる ＋ 異色 ＋ 同表情",
      "undiscovered": "似ていないところまで揃える必要はない。",
      "discovered": "全然おそろいではなかった。",
      "audit": "成立可能",
      "active": true
    },
    {
      "id": 22,
      "rarity": 2,
      "name": "折り合い",
      "trigger": "くっつく",
      "score": 440,
      "andCount": 4,
      "condition": "ごきげんと不機嫌 ＋ 異色 ＋ サイズ差が小さい ＋ 低速",
      "undiscovered": "気分が違っても話はできる。",
      "discovered": "なんとか折り合った。",
      "audit": "成立可能",
      "active": true
    },
    {
      "id": 23,
      "rarity": 2,
      "name": "やっぱ無理",
      "trigger": "何も起こらない",
      "score": 330,
      "andCount": 3,
      "condition": "過去に接着経験あり ＋ 同じ相手との再接触 ＋ 現在の表情が前回接着時と異なる",
      "undiscovered": "一度うまくいったからといって。",
      "discovered": "今回は無理だった。",
      "audit": "成立可能",
      "active": true
    },
    {
      "id": 24,
      "rarity": 2,
      "name": "平行線",
      "trigger": "何も起こらない",
      "score": 400,
      "andCount": 4,
      "condition": "同色 ＋ 同表情 ＋ 接触3回目以上 ＋ 一度もくっついていない",
      "undiscovered": "似ている者同士ほど難しいこともある。",
      "discovered": "最後まで平行線だった。",
      "audit": "成立可能",
      "active": true
    },
    {
      "id": 25,
      "rarity": 2,
      "name": "笑顔で殴るな",
      "trigger": "何も起こらない",
      "score": 450,
      "andCount": 4,
      "condition": "ごきげん ＋ 相手もごきげん ＋ 高速衝突 ＋ サイズ差が大きい",
      "undiscovered": "笑顔にもいろいろある。",
      "discovered": "笑顔で殴って何も起きなかった。",
      "audit": "成立可能",
      "active": true
    },
    {
      "id": 26,
      "rarity": 2,
      "name": "何もなかった",
      "trigger": "何も起こらない",
      "score": 480,
      "andCount": 4,
      "condition": "高速衝突 ＋ 両方壁接触済み ＋ 異色 ＋ 異表情",
      "undiscovered": "派手だから何か起きるとは限らない。",
      "discovered": "本当に何もなかった。",
      "audit": "成立可能",
      "active": true
    },
    {
      "id": 27,
      "rarity": 2,
      "name": "巻き添え",
      "trigger": "弾ける",
      "score": 420,
      "andCount": 3,
      "condition": "誘爆2体以上 ＋ 誘爆ぽちょに2色以上 ＋ 起爆ぽちょと異表情が含まれる",
      "undiscovered": "近くにいるだけでも危ない。",
      "discovered": "巻き添えが増えた。",
      "audit": "成立可能",
      "active": true
    },
    {
      "id": 28,
      "rarity": 2,
      "name": "短い生涯",
      "trigger": "弾ける",
      "score": 350,
      "andCount": 3,
      "condition": "射出から短時間 ＋ 壁未接触 ＋ 接触回数2回以下",
      "undiscovered": "世の中には早い別れもある。",
      "discovered": "かなり短かった。",
      "audit": "成立可能",
      "active": true
    },
    {
      "id": 29,
      "rarity": 2,
      "name": "大往生",
      "trigger": "弾ける",
      "score": 500,
      "andCount": 4,
      "condition": "長時間生存 ＋ 接触回数が一定以上 ＋ 天井接触経験あり ＋ 起爆ぽちょが単独ではない",
      "undiscovered": "急ぐ必要はない。",
      "discovered": "よく生きた。",
      "audit": "成立可能",
      "active": true
    },
    {
      "id": 30,
      "rarity": 2,
      "name": "最後まで普通",
      "trigger": "弾ける",
      "score": 380,
      "andCount": 4,
      "condition": "初期表情ふつう ＋ 現在表情ふつう ＋ 表情変化なし ＋ 生存時間が一定以上",
      "undiscovered": "普通を貫くのも難しい。",
      "discovered": "最後まで普通だった。",
      "audit": "成立可能",
      "active": true
    },
    {
      "id": 31,
      "rarity": 3,
      "name": "気まずい再会",
      "trigger": "くっつく",
      "score": 900,
      "andCount": 5,
      "condition": "過去に同じ相手と接着 ＋ 一度離れている ＋ 一定時間以上離れていた ＋ 再接触時に表情が異なる ＋ 低速接触",
      "undiscovered": "会わない方がよかったのかもしれない。",
      "discovered": "気まずいまま、また一緒になった。",
      "audit": "成立可能",
      "active": true
    },
    {
      "id": 32,
      "rarity": 3,
      "name": "三者面談",
      "trigger": "くっつく",
      "score": 1100,
      "andCount": 4,
      "condition": "新しく3体グループが成立 ＋ 3体すべて異色 ＋ 表情が3種類すべて揃う ＋ サイズ区分も3種類すべて揃う",
      "undiscovered": "三人いれば話はまとまる、たぶん。",
      "discovered": "議題は不明だが三者面談は成立した。",
      "audit": "成立可能",
      "active": true
    },
    {
      "id": 33,
      "rarity": 3,
      "name": "復縁",
      "trigger": "くっつく",
      "score": 1000,
      "andCount": 5,
      "condition": "同じ2体が過去に接着済み ＋ その後離れた ＋ 離れている間に双方が別ぽちょへ接触 ＋ 再会 ＋ 再び接着",
      "undiscovered": "縁は切れたようで切れない。",
      "discovered": "ちゃんと戻った。",
      "audit": "成立可能",
      "active": true
    },
    {
      "id": 34,
      "rarity": 3,
      "name": "芋づる式",
      "trigger": "くっつく",
      "score": 1250,
      "andCount": 4,
      "condition": "1回の接触を起点 ＋ 1秒以内 ＋ 3体以上が順番に接着 ＋ 最終グループが3色以上",
      "undiscovered": "一つ動くと、ついてくることがある。",
      "discovered": "本当に芋づる式だった。",
      "audit": "成立可能",
      "active": true
    },
    {
      "id": 35,
      "rarity": 3,
      "name": "空気を読んだ",
      "trigger": "くっつく",
      "score": 950,
      "andCount": 5,
      "condition": "接触地点周辺に4体以上 ＋ 自分だけ異表情 ＋ 相手は周囲の多数派表情 ＋ 接着後に自分が多数派側へ入る ＋ 低速",
      "undiscovered": "周りを見るのも大事。",
      "discovered": "ちゃんと空気を読んだらしい。",
      "audit": "成立可能",
      "active": true
    },
    {
      "id": 36,
      "rarity": 3,
      "name": "ちょうどいい",
      "trigger": "くっつく",
      "score": 850,
      "andCount": 5,
      "condition": "両者の実サイズ差が非常に小さい ＋ 異色 ＋ 異表情 ＋ 過去に接触なし ＋ 接触速度が中程度",
      "undiscovered": "合う時は妙に合う。",
      "discovered": "ちょうどよかった。",
      "audit": "成立可能",
      "active": true
    },
    {
      "id": 37,
      "rarity": 3,
      "name": "仲良くないです",
      "trigger": "何も起こらない",
      "score": 1050,
      "andCount": 5,
      "condition": "過去に5回以上接触 ＋ 同色 ＋ 同表情 ＋ 一度も接着なし ＋ 一度もどちらも弾けていない",
      "undiscovered": "会う回数と仲の良さは別。",
      "discovered": "念のため言うと仲良くない。",
      "audit": "成立可能",
      "active": true
    },
    {
      "id": 38,
      "rarity": 3,
      "name": "知らないふり",
      "trigger": "何も起こらない",
      "score": 1200,
      "andCount": 5,
      "condition": "過去に接着経験あり ＋ 同じ相手との再接触 ＋ 両方ともその後別グループ所属経験あり ＋ 今回低速 ＋ それでも何も起こらない",
      "undiscovered": "知っていても知らない顔はできる。",
      "discovered": "見事に知らないふりをした。",
      "audit": "成立可能",
      "active": true
    },
    {
      "id": 39,
      "rarity": 3,
      "name": "正面突破失敗",
      "trigger": "何も起こらない",
      "score": 980,
      "andCount": 5,
      "condition": "両方高速 ＋ 正面衝突 ＋ 両方大サイズ ＋ 異色 ＋ どちらも弾けない",
      "undiscovered": "勢いだけではどうにもならない。",
      "discovered": "正面突破は失敗した。",
      "audit": "現状成立不可",
      "active": false
    },
    {
      "id": 40,
      "rarity": 3,
      "name": "謎の平和",
      "trigger": "何も起こらない",
      "score": 1300,
      "andCount": 6,
      "condition": "周囲に5体以上 ＋ 高速衝突 ＋ 装飾持ちを含む ＋ 異色 ＋ 異表情 ＋ 何も発生しない",
      "undiscovered": "騒がしいのに平和なこともある。",
      "discovered": "何故か平和だった。",
      "audit": "成立可能",
      "active": true
    },
    {
      "id": 41,
      "rarity": 3,
      "name": "色とりどり",
      "trigger": "弾ける",
      "score": 1200,
      "andCount": 4,
      "condition": "誘爆込み4体以上 ＋ 4色以上 ＋ 起爆ぽちょと同色が誘爆にいない ＋ 誘爆数3体以上",
      "undiscovered": "色が多いと見栄えはいい。",
      "discovered": "きれいに色が散った。",
      "audit": "成立可能",
      "active": true
    },
    {
      "id": 42,
      "rarity": 3,
      "name": "顔が広い",
      "trigger": "弾ける",
      "score": 1100,
      "andCount": 4,
      "condition": "起爆ぽちょが4色以上と接触済み ＋ 接触相手5体以上 ＋ 生存時間が一定以上 ＋ 誘爆あり",
      "undiscovered": "知り合いが多いと最後もにぎやかだ。",
      "discovered": "かなり顔が広かった。",
      "audit": "成立可能",
      "active": true
    },
    {
      "id": 43,
      "rarity": 3,
      "name": "波乱万丈",
      "trigger": "弾ける",
      "score": 1450,
      "andCount": 5,
      "condition": "接着経験あり ＋ 離脱経験あり ＋ 表情変化経験あり ＋ 壁3回以上 ＋ 3色以上と接触済み",
      "undiscovered": "いろいろあったらしい。",
      "discovered": "本当にいろいろあった。",
      "audit": "保留：表情変化未定義",
      "active": true
    },
    {
      "id": 44,
      "rarity": 3,
      "name": "盛大な巻き添え",
      "trigger": "弾ける",
      "score": 1500,
      "andCount": 5,
      "condition": "誘爆4体以上 ＋ 誘爆内に3色以上 ＋ 3表情中2種類以上 ＋ サイズ区分2種類以上 ＋ 起爆ぽちょが装飾なし",
      "undiscovered": "地味な原因ほど大事になることがある。",
      "discovered": "原因は普通、結果は盛大だった。",
      "audit": "成立可能",
      "active": true
    },
    {
      "id": 45,
      "rarity": 3,
      "name": "そんなつもりじゃ",
      "trigger": "弾ける",
      "score": 1350,
      "andCount": 5,
      "condition": "起爆原因が第三者から押された衝突 ＋ 起爆ぽちょは直前まで低速 ＋ 衝突相手とは初対面 ＋ 誘爆あり ＋ 起爆ぽちょが不機嫌ではない",
      "undiscovered": "本人の意思とは限らない。",
      "discovered": "たぶんそんなつもりではなかった。",
      "audit": "成立可能",
      "active": true
    },
    {
      "id": 46,
      "rarity": 4,
      "name": "壁を知る者たち",
      "trigger": "弾ける",
      "score": 3200,
      "andCount": 6,
      "condition": "起爆グループ3体以上 ＋ 全員左壁接触済み ＋ 全員右壁接触済み ＋ 全員天井接触済み ＋ 3色以上 ＋ 起爆ぽちょが最も壁接触回数が多い",
      "undiscovered": "壁にも種類がある。",
      "discovered": "全員、よく壁を知っていた。",
      "audit": "成立可能",
      "active": true
    },
    {
      "id": 47,
      "rarity": 4,
      "name": "知らぬ間に親友",
      "trigger": "くっつく",
      "score": 3600,
      "andCount": 7,
      "condition": "同じ2体が過去5回以上接触 ＋ 一度も接着経験なし ＋ 互いに最も接触回数の多い相手 ＋ 同色ではない ＋ 同表情ではない ＋ 今回低速 ＋ 初めて接着",
      "undiscovered": "仲良くなる瞬間は意外と分からない。",
      "discovered": "知らぬ間に親友だった。",
      "audit": "成立可能",
      "active": true
    },
    {
      "id": 48,
      "rarity": 4,
      "name": "全員初対面",
      "trigger": "くっつく",
      "score": 3400,
      "andCount": 6,
      "condition": "一度の連続接着で4体グループ成立 ＋ 4体全員が互いに未接触だった組み合わせを含む ＋ 3色以上 ＋ 2表情以上 ＋ 誰も過去に接着経験なし ＋ 全員装飾なし",
      "undiscovered": "初対面が多いほど会話は難しい。",
      "discovered": "全員初対面でもまとまった。",
      "audit": "成立可能",
      "active": true
    },
    {
      "id": 49,
      "rarity": 4,
      "name": "居場所を見つけた",
      "trigger": "くっつく",
      "score": 3000,
      "andCount": 6,
      "condition": "長時間単独 ＋ 接触回数5回以上 ＋ 一度も接着したことがない ＋ 既存4体以上グループへ加入 ＋ 加入先に同色なし ＋ 加入先に同表情が1体以上",
      "undiscovered": "居場所は遅れて見つかることもある。",
      "discovered": "ようやく居場所を見つけた。",
      "audit": "成立可能",
      "active": true
    },
    {
      "id": 50,
      "rarity": 4,
      "name": "三度目の正直",
      "trigger": "くっつく",
      "score": 3800,
      "andCount": 6,
      "condition": "同じ相手と過去2回接着 ＋ 2回とも一度離れている ＋ 3回目の再接着 ＋ 過去2回とは違う位置帯 ＋ 現在表情が初回と異なる ＋ 双方長時間生存",
      "undiscovered": "二度あることが三度あるとは限らない。",
      "discovered": "三度目はちゃんと正直だった。",
      "audit": "保留：表情変化未定義",
      "active": true
    },
    {
      "id": 51,
      "rarity": 4,
      "name": "絶対に仲良くならない",
      "trigger": "何も起こらない",
      "score": 4000,
      "andCount": 7,
      "condition": "同じ相手と接触10回以上 ＋ 一度も接着なし ＋ 一度も相互誘爆なし ＋ 同色 ＋ 同表情 ＋ サイズ区分同じ ＋ 今回も低速接触",
      "undiscovered": "そこまで会えば何かありそうなものだ。",
      "discovered": "絶対に仲良くならなかった。",
      "audit": "成立可能",
      "active": true
    },
    {
      "id": 52,
      "rarity": 4,
      "name": "何が気に入らないの",
      "trigger": "何も起こらない",
      "score": 4200,
      "andCount": 7,
      "condition": "両方装飾付き ＋ 同じ装飾 ＋ 同色 ＋ 同表情 ＋ サイズ差が小さい ＋ 過去に複数回接触 ＋ それでも一度も接着していない",
      "undiscovered": "揃っていればいいというものでもない。",
      "discovered": "何が気に入らないのかは分からない。",
      "audit": "成立可能",
      "active": true
    },
    {
      "id": 53,
      "rarity": 4,
      "name": "完璧な不発",
      "trigger": "何も起こらない",
      "score": 4500,
      "andCount": 7,
      "condition": "高速正面衝突 ＋ 両方大 ＋ 両方不機嫌 ＋ 壁反射直後 ＋ 装飾ありを含む ＋ 周囲に4体以上 ＋ 何も起きない",
      "undiscovered": "ここまで揃えば、普通は何かある。",
      "discovered": "完璧に何も起きなかった。",
      "audit": "現状成立不可",
      "active": false
    },
    {
      "id": 54,
      "rarity": 4,
      "name": "生還",
      "trigger": "何も起こらない",
      "score": 3900,
      "andCount": 7,
      "condition": "起爆条件候補を過去に複数回満たした履歴 ＋ 接触回数10回以上 ＋ 高速衝突 ＋ 相手が不機嫌 ＋ 天井付近 ＋ 装飾持ち ＋ それでも生存",
      "undiscovered": "危ない目に何度も遭う者もいる。",
      "discovered": "今回も生き残った。",
      "audit": "条件文要修正",
      "active": false
    },
    {
      "id": 55,
      "rarity": 4,
      "name": "大家族",
      "trigger": "弾ける",
      "score": 4800,
      "andCount": 6,
      "condition": "接着グループ6体以上 ＋ 4色以上 ＋ 3表情すべて含む ＋ 3サイズすべて含む ＋ 装飾ありが1体以上 ＋ 起爆ぽちょがグループ最古参",
      "undiscovered": "人数が増えると何かと大変。",
      "discovered": "大家族はまとめて弾けた。",
      "audit": "成立可能",
      "active": true
    },
    {
      "id": 56,
      "rarity": 4,
      "name": "最後の一人",
      "trigger": "弾ける",
      "score": 4600,
      "andCount": 6,
      "condition": "起爆ぽちょが過去に所属したグループの他メンバーが全員既に消滅 ＋ 生存時間が長い ＋ 接着経験3回以上 ＋ 3色以上と接触 ＋ 表情変化経験あり ＋ 今回誘爆なし",
      "undiscovered": "最後まで残るのが幸運とは限らない。",
      "discovered": "最後の一人もいなくなった。",
      "audit": "保留：表情変化未定義",
      "active": true
    },
    {
      "id": 57,
      "rarity": 4,
      "name": "巡り巡って",
      "trigger": "弾ける",
      "score": 5000,
      "andCount": 6,
      "condition": "AがBを押す ＋ BがCに衝突 ＋ CがDに接触 ＋ Dが起爆 ＋ AとDは直接接触していない ＋ 4体すべて異なる色",
      "undiscovered": "原因は遠くにあるかもしれない。",
      "discovered": "巡り巡って、そこが弾けた。",
      "audit": "成立可能・因果追跡必要",
      "active": true
    },
    {
      "id": 58,
      "rarity": 4,
      "name": "ぽちょ渋滞",
      "trigger": "弾ける",
      "score": 4400,
      "andCount": 6,
      "condition": "接触地点周囲に8体以上 ＋ 起爆グループ4体以上 ＋ 他グループ2つ以上が至近距離 ＋ 全体で4色以上 ＋ 低速ぽちょが過半数 ＋ 爆発によって密集が解消される",
      "undiscovered": "混んでいるところでは何か起こる。",
      "discovered": "渋滞は強制的に解消された。",
      "audit": "成立可能・事後判定必要",
      "active": true
    },
    {
      "id": 59,
      "rarity": 5,
      "name": "ぽちょ同窓会",
      "trigger": "くっつく",
      "score": 9000,
      "andCount": 8,
      "condition": "4体以上のグループ成立 ＋ 全員が過去に同じグループへ所属した経験あり ＋ その後全員一度離散 ＋ 離散後それぞれ別のぽちょへ接触 ＋ 再集合 ＋ 3色以上 ＋ 2表情以上 ＋ 元グループと同じ構成メンバー",
      "undiscovered": "昔の顔ぶれは案外忘れない。",
      "discovered": "同窓会の出席率が高すぎる。",
      "audit": "成立可能",
      "active": true
    },
    {
      "id": 60,
      "rarity": 5,
      "name": "奇跡の再結成",
      "trigger": "くっつく",
      "score": 12000,
      "andCount": 9,
      "condition": "過去に5体以上のグループだった ＋ 全員完全にバラバラになった ＋ そのうち誰も弾けていない ＋ 一定時間以上離散 ＋ 再び同じメンバーだけで接着 ＋ 接着順が前回と異なる ＋ 3色以上 ＋ 装飾ありが含まれる ＋ 最後の1体加入で成立",
      "undiscovered": "もう一度同じ形になるとは限らない。",
      "discovered": "本当に再結成した。",
      "audit": "成立可能",
      "active": true
    },
    {
      "id": 61,
      "rarity": 5,
      "name": "誰も望んでいない再会",
      "trigger": "くっつく",
      "score": 11500,
      "andCount": 9,
      "condition": "両者が過去に接着 ＋ その接着後に双方とも不機嫌へ表情変化 ＋ 離脱 ＋ それぞれ別グループ所属 ＋ 双方そのグループからも離脱 ＋ 長時間経過 ＋ 再接触 ＋ 現在も双方不機嫌 ＋ 再び接着",
      "undiscovered": "会いたくない相手ほど会うことがある。",
      "discovered": "誰も望んでいなさそうだった。",
      "audit": "保留：表情変化未定義",
      "active": true
    },
    {
      "id": 62,
      "rarity": 5,
      "name": "ここまでして何もない",
      "trigger": "何も起こらない",
      "score": 12500,
      "andCount": 10,
      "condition": "同色 ＋ 同表情 ＋ 同装飾 ＋ 同サイズ区分 ＋ 過去接触5回以上 ＋ 過去接着経験あり ＋ 一度離れている ＋ 低速再接触 ＋ 天井付近 ＋ それでも無反応",
      "undiscovered": "期待のしすぎはよくない。",
      "discovered": "本当にここまでして何もなかった。",
      "audit": "成立可能だが狭い",
      "active": true
    },
    {
      "id": 63,
      "rarity": 5,
      "name": "何も起こらない奇跡",
      "trigger": "何も起こらない",
      "score": 14000,
      "andCount": 9,
      "condition": "両方装飾あり ＋ 高速正面衝突 ＋ 大サイズ同士 ＋ 不機嫌同士 ＋ 双方壁3回以上 ＋ 双方天井接触済み ＋ 過去接触あり ＋ 周囲に5体以上 ＋ どの挙動条件にも該当しない",
      "undiscovered": "何も起きない方が珍しい時もある。",
      "discovered": "奇跡的に何も起きなかった。",
      "audit": "現状成立不可",
      "active": false
    },
    {
      "id": 64,
      "rarity": 5,
      "name": "完璧な他人",
      "trigger": "何も起こらない",
      "score": 10500,
      "andCount": 9,
      "condition": "長時間同じ盤面に存在 ＋ 互いに一度も接触したことがない ＋ 両者とも接触相手5体以上 ＋ 両者とも3色以上と接触 ＋ 今回が初接触 ＋ 同色 ＋ 同表情 ＋ 同サイズ区分 ＋ それでも無反応",
      "undiscovered": "近くにいるからといって知り合いとは限らない。",
      "discovered": "初めまして。",
      "audit": "成立可能",
      "active": true
    },
    {
      "id": 65,
      "rarity": 5,
      "name": "一族郎党",
      "trigger": "弾ける",
      "score": 15000,
      "andCount": 8,
      "condition": "接着グループ8体以上 ＋ 5色以上 ＋ 3表情すべて ＋ 3サイズすべて ＋ 装飾2種類以上 ＋ 起爆ぽちょがグループ最古参 ＋ 起爆ぽちょが全員と直接または間接接着 ＋ 誘爆7体以上",
      "undiscovered": "多ければ多いほど大変になる。",
      "discovered": "一族郎党まとめて消えた。",
      "audit": "成立可能",
      "active": true
    },
    {
      "id": 66,
      "rarity": 5,
      "name": "波乱万丈・完",
      "trigger": "弾ける",
      "score": 18000,
      "andCount": 9,
      "condition": "全6色と接触済み ＋ 3表情すべて経験済み ＋ 接着3回以上 ＋ 離脱3回以上 ＋ 左右壁接触済み ＋ 天井接触済み ＋ 装飾あり ＋ 長時間生存 ＋ 最後は誘爆ではなく自分が起爆",
      "undiscovered": "まだやっていないことがあるかもしれない。",
      "discovered": "だいたい全部やった。",
      "audit": "保留：表情変化未定義",
      "active": true
    },
    {
      "id": 67,
      "rarity": 5,
      "name": "全部見た",
      "trigger": "弾ける",
      "score": 20000,
      "andCount": 8,
      "condition": "起爆ぽちょが6色全てに接触 ＋ ごきげん・ふつう・不機嫌を全経験 ＋ 小中大すべてのサイズ区分と接触 ＋ 装飾4種すべてと接触 ＋ 接着経験あり ＋ 誘爆経験を目撃済み ＋ 壁3種類以上へ接触 ＋ 生存時間一定以上",
      "undiscovered": "見ようと思って見られるものではない。",
      "discovered": "本当に全部見たらしい。",
      "audit": "保留：表情変化＋目撃定義",
      "active": true
    },
    {
      "id": 68,
      "rarity": 5,
      "name": "玉突きの果て",
      "trigger": "弾ける",
      "score": 17000,
      "andCount": 8,
      "condition": "起点ぽちょと起爆ぽちょが別 ＋ 因果経路5体以上 ＋ 途中で壁反射を1回以上挟む ＋ 起点と起爆は直接接触なし ＋ 経路中4色以上 ＋ 経路中2表情以上 ＋ 起爆時誘爆3体以上 ＋ 起点ぽちょはまだ生存",
      "undiscovered": "最初の一押しは忘れられがち。",
      "discovered": "ずいぶん遠くまで原因が続いた。",
      "audit": "成立可能・因果追跡必要",
      "active": true
    },
    {
      "id": 69,
      "rarity": 5,
      "name": "みんな違ってみんないい",
      "trigger": "弾ける",
      "score": 22000,
      "andCount": 8,
      "condition": "誘爆込み6体 ＋ 6色全て1体ずつ ＋ 表情3種が2体ずつ ＋ 小中大が2体ずつ ＋ 装飾ありが2体以上 ＋ 同じ装飾なし ＋ 起爆ぽちょが装飾なし ＋ 全員異なる射出順区分",
      "undiscovered": "揃っていないことが揃うこともある。",
      "discovered": "見事に全員違った。",
      "audit": "要仕様定義",
      "active": false
    },
    {
      "id": 70,
      "rarity": 5,
      "name": "ぽちょ事変",
      "trigger": "弾ける",
      "score": 25000,
      "andCount": 8,
      "condition": "1回の起爆から5体以上消滅 ＋ その直前3秒以内に別の接着イベント ＋ さらに別の無反応イベント ＋ 起爆グループ4色以上 ＋ 3表情全て ＋ 装飾あり ＋ 起爆ぽちょが表情変化経験あり ＋ 直近10秒以内に1000点以上獲得済み",
      "undiscovered": "何かが続くと、事件になる。",
      "discovered": "これはもう事変だった。",
      "audit": "保留：表情変化未定義",
      "active": true
    }
  ],
  "balance": {
    "version": "0.1.3",
    "targetOutcome": "NONE≈50% / STICK≈30〜35% / POP≈15〜20%",
    "launchPopProtectionSeconds": 0.4,
    "popGates": {
      "size": 8.8,
      "color": 7.8,
      "expression": 7.4,
      "decoration": 7.0
    },
    "specialPopGate": "追加なし"
  }
};
